services:
  iris:
    image: containers.intersystems.com/intersystems/iris-community:2025.1
    platform: linux/amd64
    container_name: iris-community-2025.1
    ports:
      - "1975:1972"   # IRIS superserver port
      - "52776:52773" # Management Portal (web)
    environment:
      - IRIS_PASSWORD=SYS
#     volumes:
#       - iris-data:/opt/irisapp/data
#     restart: unless-stopped

# volumes:
#   iris-data: